name: Build and Deploy

env:
  CI: false
  GITHUB_USERNAME: ${{ github.repository_owner }}
  REACT_APP_GITHUB_TOKEN: ${{ secrets.REACT_APP_GITHUB_TOKEN }} # Automatically set by Github Actions
  USE_GITHUB_DATA: "true"
  

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 12 * * 1' # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.REACT_APP_GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
